import Header from "@/components/Header";
import Footer from "@/components/Footer";
import "./globals.scss";

export const metadata = {
  title: "Nadim Chowdhury",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="mx-4 sm:max-w-4xl sm:mx-auto">
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
