import HocLayout from "./HocLayout";
import "./globals.scss";

export const metadata = {
  title: "Nadim Chowdhury",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return <HocLayout>{children}</HocLayout>;
}
